### ISSUE TITLE
Hey! Some files missing... :)

### ISSUE THREAD

**Issue by chussenot** [YounitedCredit/younited-genaibots#3]
Hello Guys,

I am currently working on running the project locally and need your assistance to proceed correctly. Could you please provide the following example files:

```bash
.env.sample
Dockerfile
```
These files will help me ensure the project runs properly on my local setup and also allow me to build a Docker image that includes all dependencies. This setup is necessary for the LLM models to operate the fastAPI efficiently.

Thank you for your support.

**Comment by chussenot** [comment]
![image](https://github.com/YounitedCredit/younited-genaibots/assets/748507/2967df50-52c1-4876-bb54-3ddc65d0da20)

**Comment by chussenot** [comment]
Is there a way to activate/desactivate plugins?

```
SLACK_SIGNING_SECRET=""
SLACK_BOT_TOKEN=""
SLACK_BOT_USER_TOKEN=""
SLACK_BOT_USER_ID=""
SLACK_AUTHORIZED_CHANNELS=""
SLACK_FEEDBACK_CHANNEL=""
SLACK_FEEDBACK_BOT_ID=""
SLACK_INTERNAL_CHANNEL=""
SLACK_WORKSPACE_NAME=""
AZURE_CHATGPT_INPUT_TOKEN_PRICE=""
AZURE_CHATGPT_OUTPUT_TOKEN_PRICE=""
AZURE_OPENAI_KEY=""
AZURE_OPENAI_ENDPOINT=""
AZURE_CHATGPT_MODEL_NAME=""
AZURE_CHATGPT_VISION_MODEL_NAME=""
OPENAI_SEARCH_OPENAI_KEY=""
OPENAI_SEARCH_OPENAI_ENDPOINT=""
OPENAI_SEARCH_OPENAI_API_VERSION=""
OPENAI_SEARCH_MODEL_HOST=""
OPENAI_SEARCH__MODEL_NAME=""
OPENAI_SEARCH_INPUT_TOKEN_PRICE=""
OPENAI_SEARCH_OUTPUT_TOKEN_PRICE=""
OPENAI_SEARCH_CONTEXT_EXTRACTION=""
OPENAI_SEARCH_CONTEXT_EXTRACTION_BEFORE_RATIO=""
OPENAI_SEARCH_CONTEXT_EXTRACTION_AFTER_RATIO=""
OPENAI_SEARCH_TEXT_WEIGHT=""
OPENAI_SEARCH_TITLE_WEIGHT=""
OPENAI_SEARCH_USE_TITLE_IN_SEARCH=""
OPENAI_SEARCH_RESULT_COUNT=""

**Comment by Pilosite** [comment]
Hello  !

could you give me more information on your actual setup and your target ecosystem ? (Genai models that will be used, target user interaction slack, teams, generic rest...) 

There's no missing file from what I see, this is related to the configuration (config.yaml / environment variables)

Depending on your target configuration I can help you set the necessary config accordingly

**Comment by Pilosite** [comment]
If you want to remove a specific plugin you can simply delete the section in your config.yaml or comment it.
For an empty plugin category you can set for example something like :

USER_INTERACTIONS:
    CUSTOM_API: {}

**Comment by Pilosite** [comment]
There's some details on the config.yaml here https://github.com/YounitedCredit/younited-genaibots/wiki/Chapter-N10:-Configuration-Deep-Dive:-Mastering-the-config.yaml-File

Doc is still in progress please be patient :-)

**Comment by chussenot** [comment]
Do you also have a Dockerfile to share?

**Comment by Pilosite** [comment]
yes, here's the dockerfile I use to push it on our container registry: 
# For more information, please refer to https://aka.ms/vscode-docker-python
FROM python:3.10-slim

EXPOSE 8000

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

# Install pip requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

WORKDIR /app
COPY . /app

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-python-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

# During debugging, this entry point will be overridden. For more information, please refer to https://aka.ms/vscode-docker-python-debug
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--timeout", "160", "-k", "uvicorn.workers.UvicornWorker", "app:app"]
