### ISSUE TITLE
 Add pytest-cov to project dependencies -- Testing with coverage.

### ISSUE THREAD

**Issue by chussenot** [YounitedCredit/younited-genaibots#6]
Changes:

- Added `pytest-cov` to the project dependencies

![image](https://github.com/YounitedCredit/younited-genaibots/assets/748507/7dacb3b4-bb15-4ca8-94e0-aecb57434da7)

---

/!\ A valid configuration env is needed to run the tests properly.

**Comment by chussenot** [comment]
These file must be ignored in the `.gitignore` I think so.

```
      modified:   .coverage
      modified:   coverage.xml

**Comment by Pilosite** [comment]
thks for the notification we will update that.

**Comment by Pilosite** [comment]
done!
